---
controller:
  max_generations: 300
  max_fitness_calls: 2500
archive:
  name: Troglitazone
  size: 150
  accuracy: 25000
descriptor:
  properties:
  - Descriptors.ExactMolWt
  - Descriptors.MolLogP
  - Descriptors.TPSA
  - Crippen.MolMR
  ranges:
  - - 225
    - 555
  - - -0.5
    - 5.5
  - - 0
    - 140
  - - 40
    - 130
fitness:
  type: Guacamol
  target: median2
arbiter:
  rules:
  - Glaxo
generator:
  batch_size: 40
  initial_size: 40
  mutation_data: data/smarts/mutation_collection.tsv
  initial_data: data/smiles/guacamol_intitial_rediscovery_troglitazone.smi
surrogate:
  type: Fingerprint
  representation: ECFP4
acquisition: 
  type: Mean
